### ISSUE TITLE
ZXT-120 can only set to cool to 25°C?

### ISSUE THREAD

**Issue by tregota** [TedTolboom/hk.com.remotec#20]
Hi!
If I set mode to Cool it always gets set to 25°C and if I set the temperature it also sets mode to Heat.
Is this a matter of what AC I have or just how early the ZXT-120 support is?
I have an Electrolux, code 88.

thanks

**Comment by TedTolboom** [comment]
@tregota we (actually all credits go to @limkopi78) are working on an update of the ZXT-120 driver that should fix this issue..

**Comment by tregota** [comment]
Great to hear. Looking forward to it.
I've been missing this support since I switched from smartthings to homey.

**Comment by toonvranken** [comment]
Any news? Same problem.
Can't Use it!

**Comment by TedTolboom** [comment]
@toonvranken I was not able to complete and test the driver update, as I like to do, before my holidays. 

This update is at the top of my list after I’m back from holidays...

**Comment by TedTolboom** [comment]
@tregota @toonvranken 
Just updated the development branch, with a complete rewritten ZXT-120 driver...
It should now support all modes and corresponding setpoints..

Could you give this one a try: https://github.com/TedTolboom/hk.com.remotec/tree/development
and report if it fixes the issues unable to set the setpoint in the cooling thermostat mode?

**Comment by toonvranken** [comment]
Hi, Thanks for this.
But how can I install it?

Op zo 12 aug. 2018 om 13:09 schreef dT <notifications@github.com>:

**Comment by TedTolboom** [comment]
Hi @toonvranken,

You can install it by executing the following steps:
1. Download the Remotec app from https://github.com/TedTolboom/hk.com.remotec/tree/development
2. Install the Command Line Interface (CLI), as explained in this guide (step 1-3, with Node.js 8.9.4): https://developer.athom.com/docs/apps/tutorial-Getting Started.html
3. Install the app, from within the folder where you downloaded the app to, via ‘Athom app install’
4. Remove the ZXT-120 from Homey and re-include based on the updated app

Once the updated version is available in the app store, you can simply install it over this manually installed version.

**Comment by tregota** [comment]
Hi @TedTolboom,
Thanks for the effort.

No luck for me with this version.
Set mode does nothing now.
Set temperature still sets the temperature but also changes to heat mode, as before.
So I can turn it on to heat if I want to by setting the temp but I can't turn it off. :)
A minor thing i just happened to notice was that the air condition swing setting acts strangely. whatever it is set to when starting the ac means off and changing it turns the swing on. even if that happens to be changing it to off. Nothing I really use but thought I should mention it.

**Comment by TedTolboom** [comment]
@tregota just to check; you tried the development branch?
Are you referring to changing through one of the flow action cards?
Or through the web UI / app?

**Comment by tregota** [comment]
@TedTolboom
yes, I uninstalled and downloaded the branch you linked to and installed via cli. 
I tested set mode and temperature via flow action cards.

**Comment by tregota** [comment]
In case this is helpful.
Setting to cool via card gives:
```
2018-08-12 21:08:43 [log] [ManagerDrivers] [ZXT-120] [0] Cool
(node:17913) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: missing_parser
(node:17913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Setting temp gives:
```
2018-08-12 21:10:55 [log] [ManagerDrivers] [ZXT-120] [0] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 64>, 'Battery Level': {} },
  '2': null }
2018-08-12 21:10:57 [log] [ManagerDrivers] [ZXT-120] [0] node.CommandClass['COMMAND_CLASS_SENSOR_MULTILEVEL'].on('report') arguments: { '0': { value: 5, name: 'SENSOR_MULTILEVEL_REPORT' },
  '1':
   { 'Sensor Type (Raw)': <Buffer 01>,
     'Sensor Type': 'Temperature (version 1)',
     'Level (Raw)': <Buffer 01>,
     Level: { Size: 1, Scale: 0, Precision: 0 },
     'Sensor Value': <Buffer 17>,
     'Sensor Value (Parsed)': 23 },
  '2': null }
```

**Comment by TedTolboom** [comment]
thanks.... was just looking into it...

I've updated the definition of the action cards in the latest commit to the development branch.
Please re-download the development branch, run it and rebuild your flows (required):

Should give for changing the Thermostat mode to Cool the following debug logging:
```
2018-08-12 21:23:46 [log] [RemotecZwave] FlowCardAction triggered for  Remotec ZXT-120EU AC Extender to change Thermostat mode to Cool
2018-08-12 21:23:46 [log] [ManagerDrivers] [ZXT-120] [0] Setting mode to: Cool
```
The Setpoint flow card is a standard Action card...  which will not give additional logging in the debug log... the logging you showed above, is the default response of the ZXT-120 to any command, reporting back battery and temperature state...

In the development logging at https://developer.athom.com/tools/zwave you should see a similar command send to your ZXT-120 after you executed the action card:
```
2018-08-12T19:29:15.251Z | Node[61]: [COMMAND_CLASS_THERMOSTAT_SETPOINT] [THERMOSTAT_SETPOINT_SET] {"type":"Buffer","data":[2,34,0,175]}
-- | --
2018-08-12T19:29:15.251Z | Node[61]: sendData to COMMAND_CLASS_THERMOSTAT_SETPOINT, params 0x01022200af
```

**Comment by tregota** [comment]
This one works great!
I can change modes, fan speeds and temperatures via action cards.
There are some things I cant do that is't really a problem for me but I'll list the ones I've noticed.
I can't set fan speed to medium for some reason.
I can't set mode to auto, results in timeout.
just like the polling of mode and target temp seems to suffer from:
```
2018-08-13 19:22:15 [err] [ManagerDrivers] [ZXT-120] [0] { Error: timeout
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1103)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1001)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'timeout' }
```

Oh wait. I think it works better when it don't poll both at the same time. I was trying to get both every 5 minutes. but setting one to every 3 minutes and the other to 5 seems to work more reliably.

Doesn't seem to get that it is off though. "Mode Report received: Cool"
Hope that helps. 
Thanks!

**Comment by TedTolboom** [comment]
@tregota guess you're going to love the latest development branch update...

In the previous update, after changing the mode, the driver would call (send a Z-wave command) for the thermostat setpoint corresponding to the new mode... as mentioned, the ZXT-120 responds to each command received with the response, but also temperature and battery reports...

So 1 change of mode would result in: 
> GET thermostat setpoint
< REPORT thermostat setpoint
< REPORT temperature
< REPORT battery
> SET thermostat mode
< REPORT temperature
< REPORT battery
.... where the report back of the temperature and battery would block the device to listen to the actual command setting the thermostat mode... resulting in the above mentioned time outs...

In the latest update, the driver build up a recollection of the different setpoints (once set or received) and will update the UI based on this recollection (without sending an additional command)...

In addition, I added another flow card that is able to set a specific setpoint (e.g. for the Cool mode)..

BTW I would not advise on polling on such a short interval; that should not be needed at all... it's only an supportive measure.

**Comment by tregota** [comment]
Sounds great.
Hey, even auto mode works with the new action card! even though it doesn't work with just set mode. :)
Ok, I'll take it easier with the polling. It was more for testing the trigger cards than anything.
Let me know if you want me to test anything specific.

**Comment by toonvranken** [comment]
With flows it works great. Only Manual set temp with device it doesn't do anything

**Comment by tregota** [comment]
@TedTolboom Yep that fixed the Auto mode. thanks.

**Comment by toonvranken** [comment]
Manual set temp in any mode isn't possible.
With a flow no problem.

Op wo 15 aug. 2018 om 18:00 schreef tregota <notifications@github.com>:

**Comment by TedTolboom** [comment]
The development branch has been fully updated (and tested)... including version bump to 2.2.0
This version will be released to the app store on Monday.

@toonvranken please check the latest version and re-include the ZXT-120 based on it...
Changing setpoints I checked for all (allowed modes)... 

The ZXT-120 does however not support setting a setpoint in the resume, Fan only and Away mode... hence the interface will show '-' in those modes.

**Comment by TedTolboom** [comment]
version 2.2.0 is available in the app store right now.

You can simply install the app over the version as installed via the CLI.
To eliminate all risks, I would advise to re-include the ZXT-120 based on the app store version.

I will close this issue since v2.2.0 provides the solution.
