### ISSUE TITLE
Unable to add Remotec Scene Master ZRC-90 AU

### ISSUE THREAD

**Issue by AndyASey** [TedTolboom/hk.com.remotec#24]
I have the AU version of the Scene controller and it will not connect to the Homey.  BW8510AU ZRC-90AU. All I can get is 

> No compatible Homey App has been found for this device.
> It has been added as a Basic Z-Wave device.

I have followed the steps in the closed issue 13, but to no avail.

I have found that the suggested step does not work as nothing happens whilst the L button is pressed and held in, it the led only comes on once the L button is released.

> Press the “L” button at the rear side of the Scene Master until the LED light up to add the device into the Z-Wave network.

Am I doing something wrong?

**Comment by AndyASey** [comment]
This is what is in the Node information.  is this the info you need?

Manufacturer ID    21076
product type ID     2
Product ID             34064

Thankyou for the quick response

**Comment by Tiggerito** [comment]
Just adding a me too. 

BW8510AU ZRC-90AU

Same node information.

**Comment by TedTolboom** [comment]
v2.2.1 is available in the app store, will close this issue.
If not fixed, please re-open.

**Comment by Tiggerito** [comment]
Working for me. Thanks.
