### ISSUE TITLE
Instruction to add the remote can be better

### ISSUE THREAD

**Issue by vdneut** [TedTolboom/hk.com.remotec#25]
Just installed the remote and had some trouble which can be avoided if the instruction is changed a little.
Currently it says 'Push the 'L' button until the light flashes'. 
This implies that the button must be pressed until the light flashes, but that won't happen.
It should be 'Push the 'L' button and let go' then the light flashes and the device is in Learning mode.

**Comment by TedTolboom** [comment]
Update is available in the app store.
I'll close this issue, please re-open when issue is not solved
