### ISSUE TITLE
Temperature updates

### ISSUE THREAD

**Issue by ToonVos** [TedTolboom/hk.com.remotec#26]
I use the ZXT-120 for steering an AC. I suspect the device is not giving enough readings for temperature because the reported temperature doesn't drop after AC is activated (the temperature in the room does of course)
Would it be possible to push the device for a reading in a certain interval?

**Comment by TedTolboom** [comment]
@ToonVos will be added in next release (v2.2.1). 

Set to 0 (disabled) on default... So you'll need to set your own polling interval.
<img width="567" alt="schermafbeelding 2018-09-23 om 09 14 10" src="https://user-images.githubusercontent.com/17163431/45925212-27ed1c00-bf11-11e8-9be1-a1fa6aaf94dd.png">

**Comment by TedTolboom** [comment]
Update is available in the app store.
I'll close this issue, please re-open when issue is not solved

**Comment by ToonVos** [comment]
Hi Ted,
I just tried to set the temperature polling interval in v221 but unfortunately I get the following fault message:
_failed_to_set_IR_code_learning_status_to_not provided_size_1failed_to_set_Library_version_to_not provided_size_4

**Comment by TedTolboom** [comment]
Ok, will fix that this evening.

**Comment by TedTolboom** [comment]
fixed in v2.2.2

**Comment by TedTolboom** [comment]
and in the app store... thanks!

**Comment by ToonVos** [comment]
Solved, merci
