### ISSUE TITLE
Remotec ZXT-120 Product Id for AUS/NZ units

### ISSUE THREAD

**Issue by danone1973** [TedTolboom/hk.com.remotec#27]
Hey Ted, if you can please add the AUS/NZ product Id 258 for ZXT-120 on your next update. Thank you.

**Comment by TedTolboom** [comment]
It is in the works, but I need to finalize a fix first on the ZXT-120..

I expect to release the app update for approval by Athom (App Store) this weekend.

**Comment by TedTolboom** [comment]
Will be added in v2.2.1

**Comment by TedTolboom** [comment]
Update is available in the app store.
I'll close this issue, please re-open when issue is not solved

**Comment by rzlo** [comment]
Thanks for the quick turn around, Ted! worked straight away!
cheers
