### ISSUE TITLE
Rendering Issue in Device Control Pop-Up

### ISSUE THREAD

**Issue by mattstralia** [TedTolboom/hk.com.remotec#30]
I have experienced an issue where the device control panel in the Homey Devices page doesn't display the controls for the ZXT-120 correctly. All other Remotec devices I have and other 3rd party devices are displaying correctly.

Is there a way I can investigate if this is just me?

Remotec App is v2.2.2
Homey is running on x1.5.12

![annotation 2018-11-16 201512](https://user-images.githubusercontent.com/45094298/48613676-58ff3f80-e9dc-11e8-834c-ac7f8b0a0136.jpg)

**Comment by TedTolboom** [comment]
@mattstralia this is not an app/driver issue, but a Homey V1 UI limitation.
The width of the card is limited, adding a number of menu options like on this picture the setpoint, thermostat mode and fan mode, simply leaves too little space for the sensor icons, hence the horizontal scrollbar.

I can't do anything to change this / influence this on Homey SW v1.

With Homey SW v2, these mobile cards will become obsolete and all information will be shown in a different way.

I hope this answers your question, I'll close the issue for now.

If it doesn't, please re-open the issue.
