### ISSUE TITLE
Unknown battery type in Remotec Scene Master

### ISSUE THREAD

**Issue by ElvisPresly** [TedTolboom/hk.com.remotec#38]
Hi, please add the type of battery for the Remotec Scene Master and that is where 2 x AAA is used.
Homey - Energy - Batteries
thanks

![IMG_1143](https://user-images.githubusercontent.com/18265958/94341256-883b5a80-0010-11eb-9e1a-55fba8111804.PNG)

**Comment by TedTolboom** [comment]
Fixed in the latest release

**Comment by ElvisPresly** [comment]
Hi, today updated the app. I still get an unknown battery

**Comment by TedTolboom** [comment]
Likely the battery info will only be updated upon new inclusion of the device. 
Unfortunately that will require to rebuild all your flows; no option to update the battery info is provided by Athom... sorry
