### ISSUE TITLE
Battery state incorrect

### ISSUE THREAD

**Issue by Robinyoh** [TedTolboom/hk.com.remotec#5]
Battery state is giving 20 % all the time, also after new full batteries put in place. Also some times giving battery alarm with zero in tag after pressing button. Looking in the devices page there is still 20% in device to read.

I have reinstalled the app, but this isn't fixing the problem.

Using Homey Firmware 1.5.5 and Remotec driver 2.0.1

**Comment by TedTolboom** [comment]
@Robinyoh can you check if this issue is still present?

**Comment by Robinyoh** [comment]
@TedTolboom Yes it is, the battery indicator is still giving 20%. In the version before 2.0.1 it was working correct. I don't know witch version it was...

**Comment by TedTolboom** [comment]
@Robinyoh strange... using the default battery capabilities... and here it shows nicely 95%...

Can you check the Z-wave logging to show what data is reported for this node?

**Comment by Robinyoh** [comment]
I put the batteries out en in the device and now it is working correctly! Thanks for the fix!
