### ISSUE TITLE
wake up interval can not be changed

### ISSUE THREAD

**Issue by RT744** [TedTolboom/hk.com.remotec#6]
In the settings the „save settings“ button is greyed out for every value in the „wake up interval“ field exept zero.
Remotec App v2.0.1; Homey 1.5.4

**Comment by TedTolboom** [comment]
Hi RT744, 

the Remotec Scene Master does not support any other wake-up interval then 0. Therefore it is not possible to change it.

Why would you like to change it?

Battery reports are send with every button press

**Comment by RT744** [comment]
If „0“ stands for „never“ and not „minimal period“ then it is my bad. I feared that enabled+0s leads to „allways on“ and quickly drained batteries.
But If „0“ stands for „never“, what is the use of the checkbox „enabled“?
